version: 2

orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10
  
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet --info
          working_directory: REPLACE_THIS_WITH_A_WORKING_DIRECTORY
      - run:
          name: Build Application
          command: pwd
