version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10
  whitesource-scan: whitesource/whitesource-scan@18.10.2
  
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout
      - run:
          name: Download WS UA
          command: curl -LJO https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss_agent.sh
      - run:
          name: dotnet info
          command: dotnet --info
      - run:
          name: location
          command: pwd
      - run:
          name: list of files
          command: ls -ltr
      - run:
          name: Restore Packages
          command: dotnet restore src/bc-readme-gen/ -v n
      - run:
          name: Build Application
          command: dotnet build src/bc-readme-gen/ -v n

workflows:
  build-and-deploy:
    jobs:
    - run-tests
    - whitesource-scan/scan:
        api_key: a420fcc1a4194e2898fef7b0d044356d83023a9d21fe4f869567fae104789d8c
    - aws-ecr/build_and_push_image:
        requires:
        - run-tests
        - whitesource-scan/scan
        
        
